# v0.1.1
DROP TABLE IF EXISTS user;

CREATE TABLE user (
  id MEDIUMINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR (100) NOT NULL,
  name VARCHAR (60) NOT NULL,
  password VARCHAR (60) NOT NULL,
  mobile VARCHAR (30) NOT NULL DEFAULT "",
  avatar VARCHAR (150) NOT NULL DEFAULT "",
  wechatid VARCHAR (50) NOT NULL DEFAULT "",
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  admin BOOLEAN NOT NULL DEFAULT FALSE,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;