// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/6a36f6d5b61602b6c4ad932599097135e80abaf4/react/react-addons-create-fragment.d.ts
declare namespace __React {
    namespace __Addons {
        export function createFragment(object: { [key: string]: ReactNode }): ReactFragment;
    }
}

declare module "react-addons-create-fragment" {
    var createFragment: typeof __React.__Addons.createFragment;
    export = createFragment;
}
