DROP TABLE IF EXISTS user;

CREATE TABLE user (
  id MEDIUMINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  mail VARCHAR (100) NOT NULL,
  name VARCHAR (60) NOT NULL,
  password VARCHAR (60) NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  admin BOOLEAN NOT NULL DEFAULT FALSE
);
